In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

AttributeError: 'Series' object has no attribute 'value'

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d','b','a','c'])

In [9]:
obj2


d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['b']

7

In [13]:
obj2['b','d']

KeyError: ('b', 'd')

In [14]:
obj2[['b','d']]

b    7
d    4
dtype: int64

In [15]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [16]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

NameError: name 'np' is not defined

In [18]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'e' in obj2

False

In [20]:
'a' in obj2

True

In [21]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon': 16000, 'Utah':5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [24]:
cities = ['LA', 'BOS', 'GS', 'OKC']

In [25]:
obj4 = pd.Series(sdata, index = cities)

In [26]:
obj4

LA    NaN
BOS   NaN
GS    NaN
OKC   NaN
dtype: float64

In [27]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [28]:
obj4 = pd.Series(sdata, index = states)

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'
obj4.index.name = 'state'

In [36]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [39]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [40]:
print("read to Page 136")

read to Page 136


In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'].
       'year':[2000,2001,2002,2001,2002,2003]
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
       }
frame = pd.DataFrame(data)

In [ ]:
frame

In [ ]:
np.array([1])

In [2]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'].
       'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
       }
frame = pd.DataFrame(data)

SyntaxError: invalid syntax (<ipython-input-3-25ecf0fb4606>, line 2)

In [4]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'].
       'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
       }
frame = pd.DataFrame(data)

SyntaxError: invalid syntax (<ipython-input-4-860fef013d3d>, line 2)

In [5]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'].
       'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2] }

SyntaxError: invalid syntax (<ipython-input-5-4504d4cba2c8>, line 2)

In [6]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2] }

In [7]:
frame = pd.DataFrame(data)

In [8]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [9]:
frame.heard(
)

AttributeError: 'DataFrame' object has no attribute 'heard'

In [10]:
frame.heard()

AttributeError: 'DataFrame' object has no attribute 'heard'

In [11]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [12]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [13]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop','debt'],)

In [14]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop','debt'],
                     index =['one', 'two','three','four','five','six']
                     )

In [15]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [16]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [17]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [18]:
frame2.year


one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [19]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [20]:
frame2['debt'] = 16.5

In [21]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [22]:
frame2['debt'] = np.arange(6.)

NameError: name 'np' is not defined

In [23]:
import numpy as np


In [24]:
frame2['debt'] = np.arange(6.)

In [25]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [26]:
del frame2.estern

AttributeError: estern

In [27]:
del frame2['estern']

KeyError: 'estern'

In [28]:
del frame2['eastern']

KeyError: 'eastern'

In [29]:
pop={'Nevada':{2001:2.4,2002:2.9},
    'Ohio':{2000:1.5,2001:1.7,2002:3.6}
    }

In [30]:
frame3 = pd.DataFrame(pop)

In [31]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [32]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [2]:
series3 = frame['d']

NameError: name 'frame' is not defined

In [3]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [4]:
frame


b         d         e
Utah   -1.765845  0.449434  1.458563
Ohio    0.486224 -0.051603 -0.237779
Texas   0.023640 -1.342120 -0.837859
Oregon  1.587139 -1.175040 -0.643075

In [5]:
np.abs(frmaec
    )

NameError: name 'frmae' is not defined

In [6]:
np.abs(frmaec)

NameError: name 'frmaec' is not defined

In [7]:
np.abs(frame)

b         d         e
Utah    1.765845  0.449434  1.458563
Ohio    0.486224  0.051603  0.237779
Texas   0.023640  1.342120  0.837859
Oregon  1.587139  1.175040  0.643075

In [8]:
f = lambda x.max() - x.min()

SyntaxError: invalid syntax (<ipython-input-8-2dfa66d5a552>, line 1)

In [9]:
f = lambda x: x.max() - x.min()

In [10]:
frame.apply(f)

b    3.352984
d    1.791554
e    2.296422
dtype: float64

In [11]:
frame.apply(f, axis = 'columns')

Utah      3.224408
Ohio      0.724003
Texas     1.365760
Oregon    2.762179
dtype: float64

In [12]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [13]:
help lambda

SyntaxError: invalid syntax (<ipython-input-13-2b729eac352d>, line 1)

In [14]:
lambda

SyntaxError: invalid syntax (<ipython-input-14-444025390096>, line 1)

In [15]:
frame.apply(f)

b         d         e
min -1.765845 -1.342120 -0.837859
max  1.587139  0.449434  1.458563

In [16]:
format = lambda x: '%.2f' % x

In [17]:
frame.applymap(format)

b      d      e
Utah    -1.77   0.45   1.46
Ohio     0.49  -0.05  -0.24
Texas    0.02  -1.34  -0.84
Oregon   1.59  -1.18  -0.64

In [18]:
frame['e'].map(format)

Utah       1.46
Ohio      -0.24
Texas     -0.84
Oregon    -0.64
Name: e, dtype: object

In [19]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [20]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [21]:
frame = pd.DataFrame(np.arange(8).reshape(2,4),
                     index = ['three','one'],
                     columns = ['d','a','b','c'])

In [22]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [23]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [24]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [25]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [26]:
obj = pd.Series([4, 7, -3, 2])

In [27]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [28]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [29]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [30]:
fr = pd.DataFrame({'b': [4, 7, -3, 2],
                   'a': [0, 1, 0, 1]})

In [31]:
fr

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [32]:
fr.sort_values(by = 'b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [33]:
fr.sort_values(by = ['b','a'])

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [34]:
fr.sort_values(by = ['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [35]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [36]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [37]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [38]:
fr = pd.DataFrame({'b': [4, 7, -3, 2],
                   'a': [0, 1, 0, 1]
                   'c': [-2, 5, 8, -2.5]
                  }
                 )

SyntaxError: invalid syntax (<ipython-input-38-d5642edc5d2f>, line 3)

In [39]:
fr = pd.DataFrame({'b': [4, 7, -3, 2],
                   'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]
                  }
                 )

In [40]:
fr

a  b    c
0  0  4 -2.0
1  1  7  5.0
2  0 -3  8.0
3  1  2 -2.5

In [41]:
fr.rank(axis = 'columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [42]:
obj = pd.Series(range(5), 
                index = ['a','a','b','b','c'])

In [43]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [44]:
obj.index.is_unique

False

In [45]:
obj['a']

a    0
a    1
dtype: int64

In [46]:
obj['c']

4

In [47]:
df = pd.DataFrame(np.random.randn(4,3), 
                  index = ['a','a','b','b'])

In [48]:
df

0         1         2
a  0.577463 -0.882684 -1.218330
a  0.420586  1.078877 -0.310419
b  2.056411 -1.686654  0.298041
b  0.781140  1.315883  0.411421

In [49]:
df.loc['b']

0         1         2
b  2.056411 -1.686654  0.298041
b  0.781140  1.315883  0.411421

In [50]:
df = pd.DataFrame([ [1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]], 
                  index = ['a','b','c','d'],
                 columns = ['one', 'two'])

In [51]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [52]:
..

SyntaxError: invalid syntax (<ipython-input-52-3d80792ead7e>, line 1)

In [53]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [54]:
df.sum(axis =1 )

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [55]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [56]:
df.mean(axis ='columns',skipna = False )

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [57]:
df.idxmax()

one    b
two    d
dtype: object

In [58]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [59]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [60]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [61]:
obj = pd.Series(['a','a','b','c']*4)

In [62]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [63]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [64]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [65]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.item()})
volumn = pd.DataFrame({ticker: data['Volumn']
                      for ticker, data in all_data.items()})

AttributeError: 'dict' object has no attribute 'item'

In [66]:
import pandas_datareader.data as web

In [67]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.item()})
volumn = pd.DataFrame({ticker: data['Volumn']
                      for ticker, data in all_data.items()})

AttributeError: 'dict' object has no attribute 'item'

In [68]:
returns = price.pct_change()

NameError: name 'price' is not defined

In [69]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [70]:
uniques = obj.unique()

In [71]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [72]:
uniques.sort()

In [73]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [74]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [75]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [76]:
mask = obj.isin(['b','c'])

In [77]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [78]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [79]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a' ])

In [80]:
unique_vals = pd.Series(['c', 'b', 'a' ])

In [81]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [82]:
unique_vals = pd.Series(['c', 'b', 'd' ])

In [83]:
pd.Index(unique_vals).get_indexer(to_match)

array([ 0, -1,  1,  1,  0, -1], dtype=int64)

In [84]:
unique_vals = pd.Series(['c', 'b', 'z' ])

In [85]:
pd.Index(unique_vals).get_indexer(to_match)

array([ 0, -1,  1,  1,  0, -1], dtype=int64)

In [86]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
                     'Qu2': [2,3,1,2,3]
                     'Qu3': [1,5,2,4,4]
                    })

SyntaxError: invalid syntax (<ipython-input-86-9ce1e8686db6>, line 3)

In [87]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
                     'Qu2': [2,3,1,2,3],
                     'Qu3': [1,5,2,4,4]
                    })

In [88]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [89]:
result = data.apply(pd.value_counts).fillna(0)

In [90]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0